apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-event-store-pvc
  labels:
    project: obp
    layer: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
