version: '3.7'

services:
    webserver:
        build: docker/webserver
        volumes: 
            - ./dist:/app/public
    nodejs:
        image: node:lts
        working_dir: /app
        volumes:
            - .:/app