version: '3.7'

services:
    frontend-webserver:
        image: node:lts
        expose:
            - 4200
        command: npx ng serve --host 0.0.0.0 --disable-host-check --poll=5000
        volumes:
            - ./frontend:/app:delegated
        working_dir: /app

    frontend-cli:
        build:
            context: docker/frontend-cli
        volumes:
            - ./frontend:/app:delegated
        working_dir: /app
        depends_on:
            - selenium-hub
            - selenium-chrome
            - frontend-webserver

    selenium-hub:
        image: selenium/hub:4

    selenium-chrome:
        image: selenium/node-chrome:4
        depends_on:
            - selenium-hub
        environment:
            HUB_HOST: selenium-hub
            HUB_PORT: 4444

    api-webserver:
        build:
            context: docker/api-webserver
        volumes:
            - ./api:/app:delegated
        working_dir: /app
        depends_on:
            - api-database
        environment:
            APP_ENV: dev
            APP_SECRET: secret
            CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$
            DATABASE_URL: postgresql://obp:password@api-database:5432/openblueprint?serverVersion=12&charset=utf8

    api-cli:
        build:
            context: docker/api-cli
        volumes:
            - ./api:/app:delegated
        working_dir: /app
        depends_on:
            - api-database
        environment:
            APP_ENV: dev
            APP_SECRET: secret
            CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$$
            DATABASE_URL: postgresql://obp:password@api-database:5432/openblueprint?serverVersion=12&charset=utf8

    api-database:
        image: postgres:12.3
        volumes:
            - api-database-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: obp
            POSTGRES_DB: openblueprint
            POSTGRES_PASSWORD: password

    yaml-linter:
        build:
            context: docker/yaml-linter
        volumes:
            - ./:/app:delegated
        working_dir: /app
volumes:
    api-database-data: ~
