version: '3.7'

services:
    frontend:
        image: node:lts
        command: npx ng serve --host 0.0.0.0 --disable-host-check --poll=5000
        volumes:
            - ./frontend:/app:delegated
        working_dir: /app

    frontend-cli:
        build:
            context: docker/dev/frontend-cli
        volumes:
            - ./frontend:/app:delegated
        working_dir: /app
        depends_on:
            - selenium-hub
            - selenium-chrome
            - frontend

    selenium-hub:
        image: selenium/hub:4

    selenium-chrome:
        image: selenium/node-chrome:4
        depends_on:
            - selenium-hub
        environment:
            HUB_HOST: selenium-hub
            HUB_PORT: 4444
