version: '2'

tasks:

  ##########
  # GLOBAL #
  ##########

  install:
    desc: Install Open Blueprint Project
    cmds:
      - task: frontend-dependencies
      - task: api-dependencies
      - task: api-database-create
      - task: api-database-migration
      - task: api-database-fixture

  serve:
    desc: Start a local development stack
    cmds:
      - docker-compose up -d frontend-webserver
      - docker-compose up -d api-webserver
    deps:
      - frontend-dependencies
      - api-dependencies

  check:
    desc: Check and fix sources
    cmds:
      - task: lint
      - task: frontend-html-linter-dry-run
      - task: api-php-static-analysis
      - task: test
      - task: api-database-test
      - task: api-composer-check

  test:
    desc: Launch tests suites
    cmds:
      - task: frontend-protractor
      - task: frontend-karma

  lint:
    desc: Lint sources
    cmds:
      - task: frontend-sass-linter
      - task: frontend-ts-linter
      - task: api-php-linter

  ############
  # FRONTEND #
  ############

  frontend-build:
    desc: |
      Build frontend into dist folder
      "BUILD_ENV=prod task frontend-build" to build in production mode (default)
      "BUILD_ENV=dev task frontend-build" to build in development mode
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx ng build {{.BUILD_OPTIONS}}
    deps:
      - frontend-dependencies
    vars:
      BUILD_OPTIONS:
        sh: |
          if [ -z $BUILD_ENV ] || [ 'prod' = $BUILD_ENV ]
          then
            echo "--configuration=production"
            exit 0
          fi
          if [ $BUILD_ENV = 'dev' ]
          then
            echo "--configuration=development"
            exit 0
          fi
          exit 1

  frontend-dependencies:
    desc: Install frontend dependencies
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npm ci
    sources:
      - frontend/package-lock.json
    generates:
      - frontend/node_modules/**/*
    method: checksum

  frontend-protractor:
    desc: Execute frontend Protractor end to end test suites
    cmds:
      - docker-compose run --rm frontend-cli npx ng e2e
    deps:
      - frontend-dependencies

  frontend-karma:
    desc: Execute frontend Karma unit test suites
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx ng test --code-coverage --watch=false
    deps:
      - frontend-dependencies

  frontend-karma-watch:
    desc: Execute frontend Karma unit test suites in watch mode
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx ng test --code-coverage
    deps:
      - frontend-dependencies

  frontend-npm-audit-check:
    desc: Execute frontend NPM security audit
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npm audit --production
    deps:
      - frontend-dependencies

  frontend-npm-audit:
    desc: Resolve frontend NPM security vulnerabilities
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npm audit fix
    deps:
      - frontend-dependencies

  frontend-sass-linter:
    desc: Apply frontend linter rules to SASS sources
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx stylelint 'src/**/*.scss' --fix
    deps:
      - frontend-dependencies

  frontend-sass-linter-dry-run:
    desc: Check frontend linter rules to SASS sources
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx stylelint 'src/**/*.scss'
    deps:
      - frontend-dependencies

  frontend-ts-linter:
    desc: Apply frontend linter rules to Typescript sources
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx tslint -p . --fix
    deps:
      - frontend-dependencies

  frontend-ts-linter-dry-run:
    desc: Check frontend linter rules to Typescript sources
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx tslint -p .
    deps:
      - frontend-dependencies

  frontend-html-linter-dry-run:
    desc: Check frontend linter rules to HTML sources
    cmds:
      - docker-compose run --rm --no-deps frontend-cli npx htmlhint 'src/**/*.html' -c .htmlhintrc
    deps:
      - frontend-dependencies

  #######
  # API #
  #######

  api-build:
    desc: |
      Build api into dist folder
      "BUILD_ENV=prod task api-build" to build in production mode (default)
      "BUILD_ENV=dev task api-build" to build in development mode
    cmds:
      - docker-compose run --rm --no-deps api-cli mkdir -p {{.BUILD_DIR}}
      - docker-compose run --rm --no-deps api-cli rm -rf {{.BUILD_DIR}}/*
      - docker-compose run --rm --no-deps api-cli cp -r bin config public fixtures src templates .env composer.json composer.lock symfony.lock {{.BUILD_DIR}}
      - docker-compose run --rm --no-deps -e APP_ENV={{.APP_ENV}} api-cli composer install {{.BUILD_OPTIONS}} --working-dir {{.BUILD_DIR}}
      - docker-compose run --rm --no-deps -e APP_ENV={{.APP_ENV}} api-cli {{.BUILD_DIR}}/bin/console cache:warmup
    deps:
      - frontend-dependencies
    vars:
      BUILD_OPTIONS:
        sh: |
          if [ -z $BUILD_ENV ] || [ 'prod' = $BUILD_ENV ]
          then
            echo "--prefer-dist --no-suggest --no-dev --optimize-autoloader --classmap-authoritative"
            exit 0
          fi
          if [ $BUILD_ENV = 'dev' ]
          then
            echo "--prefer-dist --no-suggest"
            exit 0
          fi
          exit 1
      BUILD_DIR:
        sh: |
          if [ -z $BUILD_ENV ] || [ 'prod' = $BUILD_ENV ]
          then
            echo "dist/prod"
            exit 0
          fi
          if [ $BUILD_ENV = 'dev' ]
          then
            echo "dist/dev"
            exit 0
          fi
          exit 1
      APP_ENV:
        sh: |
          if [ -z $BUILD_ENV ] || [ 'prod' = $BUILD_ENV ]
          then
            echo "prod"
            exit 0
          fi
          if [ $BUILD_ENV = 'dev' ]
          then
            echo "dev"
            exit 0
          fi
          exit 1

  api-dependencies:
    desc: Install API dependencies
    cmds:
      - docker-compose run --rm --no-deps api-cli composer install
    sources:
      - api/composer.lock
    generates:
      - api/vendor/**/*
    method: checksum

  api-database-test:
    desc: Test API database
    cmds:
      - task: api-database-create
      - task: api-database-migration
      - task: api-database-fixture
      - task: api-database-schema-validate

  api-database-create:
    desc: Create/Recreate API database
    cmds:
      - docker-compose run --rm api-cli dockerize -wait tcp://api-database:5432 bin/console doctrine:database:drop --force --if-exists
      - docker-compose run --rm api-cli dockerize -wait tcp://api-database:5432 bin/console doctrine:database:create
    deps:
      - api-dependencies

  api-database-migration:
    desc: Execute API database migrations
    cmds:
      - docker-compose run --rm api-cli dockerize -wait tcp://api-database:5432 bin/console doctrine:migration:migrate --no-interaction
    deps:
      - api-dependencies
    sources:
      - api/src/Infrastructure/Persistence/Migration

  api-database-fixture:
    desc: Generate API database fixtures
    cmds:
      - docker-compose run --rm api-cli dockerize -wait tcp://api-database:5432 bin/console hautelook:fixtures:load --no-interaction
    deps:
      - api-dependencies
    sources:
      - api/src/fixtures

  api-database-schema-validate:
    desc: Check if there is a difference between API database and ORM data mapping
    cmds:
      - docker-compose run --rm api-cli dockerize -wait tcp://api-database:5432 bin/console doctrine:schema:validate
    deps:
      - api-dependencies

  api-php-linter:
    desc: Apply API linter rules to PHP sources
    cmds:
      - docker-compose run --rm --no-deps api-cli vendor/bin/php-cs-fixer fix -v --show-progress=dots --diff-format=udiff
    deps:
      - api-dependencies

  api-php-linter-dry-run:
    desc: Check API linter rules to PHP sources
    cmds:
      - docker-compose run --rm --no-deps api-cli vendor/bin/php-cs-fixer fix -v --show-progress=dots --diff-format=udiff --dry-run
    deps:
      - api-dependencies

  api-php-static-analysis:
    desc: Analyse API PHP sources
    cmds:
      - docker-compose run --rm --no-deps api-cli vendor/bin/phpstan analyse
    deps:
      - api-dependencies

  api-composer-check:
    desc: Analyse API composer dependencies and verify that no unknown symbols are used in the sources of a package
    cmds:
      - docker-compose run --rm --no-deps api-cli vendor/bin/composer-require-checker check composer.json --config-file=.composer-require-checker.json
    deps:
      - api-dependencies
