apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: eu.gcr.io/open-blueprint/webserver:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 80