apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-relational-database
  labels:
    project: obp
    app: api-relational-database
    layer: api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: api-relational-database
  template:
    metadata:
      labels:
        project: obp
        app: api-relational-database
        layer: api
    spec:
      containers:
        - name: api-relational-database
          image: postgres:12.3
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obp-secret
                  key: api-relational-database-password
          volumeMounts:
            - name: api-relational-database-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres-data
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: api-relational-database-storage
          persistentVolumeClaim:
            claimName: api-relational-database-pvc
