apiVersion: v1
kind: Service
metadata:
  name: api-message-broker-amqp-service
  labels:
    project: obp
    app: api-message-broker-amqp-service
    layer: api
spec:
  ports:
    - port: 5672
  selector:
    app: api-message-broker
  clusterIP: None
