apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend-webserver-http-service.yaml
  - api-webserver-http-service.yaml
  - api-configmap.yaml
  - frontend-webserver-deployment.yaml
  - api-webserver-deployment.yaml
  - api-database-deployment.yaml
  - api-database-pvc.yaml
  - api-database-service.yaml
