parameters:
    container.dumper.inline_factories: true
    container.dumper.inline_class_loader: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude:
            - ../src/Core/BoundedContext/*/Domain
            - ../src/Kernel.php
            - ../src/Infrastructure/Persistence/Migration
