apiVersion: batch/v1
kind: Job
metadata:
  name: api-database-migration-job
  labels:
    project: obp
    layer: api
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: api-database-migration-job
          image: eu.gcr.io/aperture-devs/obp-api-php:stable
          command: ["/bin/sh", "-c", "./bin/console doctrine:database:drop --force --if-exists && ./bin/console doctrine:database:create && ./bin/console doctrine:migrations:migrate --no-interaction && ./bin/console hautelook:fixtures:load --no-interaction"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: obp-secret
                  key: api-database-url
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: obp-secret
                  key: api-secret
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: environment
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: api-configmap
                  key: cors
