name: Security Audit

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  frontend-audit:
    name: Frontend Security Audit
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Add Task runner
      run: |
        curl -sL https://taskfile.dev/install.sh | sh && echo "::add-path::./bin"

    - name: Audit NPM modules
      run: |
        task frontend-npm-audit-check
