name: Security Audit

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  npm-audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    - name: Audit
      uses: ./.github/actions/npm-audit
  