name: Continuous Integration checks

on: push

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    - name: Docker Build
      run: |
        docker-compose build

    - name: Docker Up
      run: |
        docker-compose up -d

    - name: Add Task runner
      run: |
        curl -sL https://taskfile.dev/install.sh | sh && echo "::add-path::./bin"

    - name: NPM audit
      run: |
        task npm-audit-check --summary
        task npm-audit-check

    - name: Typescript linter
      run: |
        task ts-linter-dry-run --summary
        task ts-linter-dry-run

    - name: SASS linter
      run: |
        task sass-linter-dry-run --summary
        task sass-linter-dry-run

    - name: HTML linter
      run: |
        task html-linter-dry-run --summary
        task html-linter-dry-run

    - name: Karma Test
      run: |
        task karma --summary
        task karma

    - name: Protractor Test
      run: |
        task protractor --summary
        task protractor

    - name: Build
      run: |
        task build --summary
        task build
