name: Continuous Integration checks

on: push

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Add Task runner
        run: |
          curl -sL https://taskfile.dev/install.sh | sh && echo "::add-path::./bin"
      - name: NPM audit
        run: |
          task frontend-npm-audit-check --summary
          task frontend-npm-audit-check
      - name: Typescript linter
        run: |
          task frontend-ts-linter-dry-run --summary
          task frontend-ts-linter-dry-run
      - name: SASS linter
        run: |
          task frontend-sass-linter-dry-run --summary
          task frontend-sass-linter-dry-run
      - name: HTML linter
        run: |
          task frontend-html-linter-dry-run --summary
          task frontend-html-linter-dry-run
      - name: Karma Test
        run: |
          task frontend-karma --summary
          task frontend-karma
      - name: Protractor Test
        run: |
          task frontend-protractor --summary
          task frontend-protractor
      - name: Build Prod
        run: |
          task frontend-build --summary
          BUILD_ENV=prod task frontend-build
      - name: Build Dev
        run: |
          task frontend-build --summary
          BUILD_ENV=dev task frontend-build

  api-ci:
    name: API CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Add Task runner
        run: |
          curl -sL https://taskfile.dev/install.sh | sh && echo "::add-path::./bin"
      - name: Database create
        run: |
          task api-database-create --summary
          task api-database-create
      - name: Database migrations
        run: |
          task api-database-migration --summary
          task api-database-migration
      - name: Database fixtures
        run: |
          task api-database-fixture --summary
          task api-database-fixture
      - name: Database schema validate
        run: |
          task api-database-schema-validate --summary
          task api-database-schema-validate
      - name: PHP linter
        run: |
          task api-php-linter-dry-run --summary
          task api-php-linter-dry-run
      - name: Build Prod
        run: |
          task frontend-build --summary
          BUILD_ENV=prod task api-build
      - name: Build Dev
        run: |
          task frontend-build --summary
          BUILD_ENV=dev task api-build
