name: Continuous Integration checks

on: push

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    - name: Docker Build
      run: |
        docker-compose build
    
    - name: Docker Up
      run: |
        docker-compose up -d

    - name: Make
      run: |
        make

    - name: NPM audit
      run: |
        make npm-audit

    - name: SASS linter
      run: |
        make sass-linter-dry-run

    - name: HTML linter
      run: |
        make html-linter-dry-run
  