name: Build and Deploy to GKE on dev stage

on:
  push:
    branches:
    - develop

env:
  GKE_PROJECT: open-blueprint
  GKE_ZONE: europe-west3-a
  GKE_CLUSTER: open-blueprint

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: GCP Authentication
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}
      
    - name: Build
      run: |
        docker build --file .deploy/build/webserver/Dockerfile --tag eu.gcr.io/"$GKE_PROJECT"/webserver:${{ github.sha }} .
    
    - name: Publish
      run: |
        gcloud auth configure-docker
        docker push eu.gcr.io/$GKE_PROJECT/webserver:${{ github.sha }}

    - name: Customize deployment manifest for dev stage
      id: manifest-customization
      uses: ./.github/actions/deploy-customization
      with:
        stage: 'dev'
        commit-hash: ${{ github.sha }}

    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        cat ${{ steps.manifest-customization.outputs.manifest-path }} | kubectl apply -f -
        kubectl get services --output wide --namespace dev